version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: prepsaga-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: prepsaga
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - prepsaga-net

volumes:
  postgres-data:

networks:
  prepsaga-net:
