name: Deploy Backend to Azure

on:
  push:
    branches: [main]
    paths:
      - '**'  # You can restrict to backend files or Dockerfile if you want

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/prep-backend:latest .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/prep-backend:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App Container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APP_NAME_BACKEND }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/prep-backend:latest'
